### ISSUE TITLE
مشکل در حالت Debug

### ISSUE THREAD

**Issue by SherafatiNia-Naser** [mohsen-shafiee/ipay#2]
سلام وقت بخیر
ممنون از اینکه این پکیج رو آماده کردین
در IPayMellat.php->sendPayRequest
 $response برای soap تعریف شده
که در خط بعد
$response برای اکسپلود $response->return تعریف شده
حالا اگه حالت دیباگ فعال باشه
متغیر $response->return
در حالت دیباگ فکر میکنم خطا میده

**Comment by mohsen-shafiee** [comment]
بله، در نسخه 1.1.0 برطرف شده. لطفا آپدیت کنید

**Comment by mohsen-shafiee** [comment]
همچنین نیم اسپیس ها هم در نسخه 1.1.0 تغییر کرده
در مستندات ذکر شده
